import requests
import json

payload = {
    'speaker_segments': [{'end': 2.86597,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 1.33034,
                       'text': 'halowo osiibye otya'},
                      {'end': 7.45597,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 3.01784,
                       'text': "bulungi nze damira okuva ku ddwaliro ly'e "
                               'butabika nkuyambe ntya leero'},
                      {'end': 10.93222,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 9.02534,
                       'text': 'amannya gange naze emmere yamwe'},
                      {'end': 12.77159,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 11.28659,
                       'text': 'This is the Democrat H Corner.'},
                      {'end': 15.37034,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'caller',
                       'start': 13.04159,
                       'text': 'kale emere yamu nkuyambe enkya leero'},
                      {'end': 17.93534,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 16.88909,
                       'text': 'Well, talk to me some more.'},
                      {'end': 19.80847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 18.47534,
                       'text': 'mbadde nsitwagolinga'},
                      {'end': 22.15409,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 20.31472,
                       'text': 'okusa gulinga kwatandika ddi'},
                      {'end': 24.39847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 22.81222,
                       'text': 'entandikwa ya ssemisa eno'},
                      {'end': 26.98034,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 24.88784,
                       'text': 'buli kintu kyatandika okunzitowerera'},
                      {'end': 29.19097,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 27.45284,
                       'text': 'okuzitawera mu ngeri ki'},
                      {'end': 33.17347,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 29.86597,
                       'text': 'This all have focusing opportunity on that, '
                               'even simple readings.'},
                      {'end': 35.02972,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 33.62909,
                       'text': 'A man ago that you say.'},
                      {'end': 38.50597,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 36.59909,
                       'text': 'buli lunaku nzuukuka nkooye'},
                      {'end': 40.46347,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 39.02909,
                       'text': 'obeerako mulekitazi'},
                      {'end': 42.47159,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 41.30722,
                       'text': 'yadda akatono'},
                      {'end': 44.73284,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 42.67409,
                       'text': 'ebiseera ebisinga wazimeesinga'},
                      {'end': 46.35284,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 44.85097,
                       'text': 'Grover chose me as singer.'},
                      {'end': 51.01034,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 47.07847,
                       'text': 'mpulira nga zitowereddwa nga ndowooza kugenda'},
                      {'end': 52.88347,
                       'language': 'eng',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 51.70222,
                       'text': 'Or where I am, Romeo.'},
                      {'end': 54.87472,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 53.74409,
                       'text': 'ebiseera ebisinga'},
                      {'end': 56.32597,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 55.22909,
                       'text': 'ssaagala kulaba bantu'},
                      {'end': 59.04284,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 56.96722,
                       'text': 'olinawo enkyukakyuka yonna mu kwebaka'},
                      {'end': 62.38409,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 59.80222,
                       'text': 'ne nkakira ddala kumpi ssaawa kkumi na nnya'},
                      {'end': 65.43847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 62.87347,
                       'text': "owulira ng'okkakkanye oluvannyuma lw'okwebaka"},
                      {'end': 71.49659,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 68.40847,
                       'text': 'nedda mbeera nkyali mukoowu'},
                      {'end': 74.34847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 71.93534,
                       'text': 'gulaadi zo zibadde zitya gye buvuddeko'},
                      {'end': 83.03909,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 79.96784,
                       'text': 'bubi ddala era nagudde test bbiri'},
                      {'end': 85.16534,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'caller',
                       'start': 83.56222,
                       'text': 'ekyo kyakuwuliza kitya'},
                      {'end': 88.75972,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 87.46034,
                       'text': "ng'atalina makulu"},
                      {'end': 90.39659,
                       'language': 'lug-eng',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 89.23222,
                       'text': 'nakaaba'},
                      {'end': 92.15159,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 91.07159,
                       'text': 'ekiro kyonna'},
                      {'end': 95.17222,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 92.62409,
                       'text': 'obuliddwa intast mu bintu bye wenjoyenganga'},
                      {'end': 100.06597,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 96.79222,
                       'text': 'mpulira nga ne groopi cations tezikyankolera'},
                      {'end': 101.98972,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 100.67347,
                       'text': 'olya bulungi'},
                      {'end': 105.95534,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 103.50847,
                       'text': 'ennaku ezimu sirya ziba na appetite'},
                      {'end': 109.63409,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 106.34347,
                       'text': 'waliwo omuntu yenna akuli ku lusegera amanyi '
                               'ku nkyukakyuka zino'},
                      {'end': 113.95409,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 110.81534,
                       'text': 'munnange gwe nsula naye yangambye nsirika '
                               'nnyo'},
                      {'end': 116.72159,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 114.57847,
                       'text': "oyogerako n'emikwano ku ngeri gy'owuliramu"},
                      {'end': 119.43847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 117.22784,
                       'text': "nedda n'amasimu ng'ewala"},
                      {'end': 122.03722,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 120.41722,
                       'text': 'owulira nga tolina ssuubi'},
                      {'end': 127.35284,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 122.89784,
                       'text': 'emirundi mingi era mbeera ndowooza nti '
                               'sisobola kumaliriza digiri eno'},
                      {'end': 129.69847,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 127.63972,
                       'text': "ekyo kiwulikika nga kizitonya gy'oli"},
                      {'end': 134.92972,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 132.29722,
                       'text': "olinamu ku birowoozo byonna eby'okwetuusaako "
                               'obulabe'},
                      {'end': 139.16534,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 135.57097,
                       'text': 'nedda okugyako okwagala okubula ku vwuri '
                               'kintu'},
                      {'end': 141.94972,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 139.43534,
                       'text': 'nkitegeera kino kizibu kyamaanyi'},
                      {'end': 145.22347,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'agent',
                       'start': 143.45159,
                       'text': 'simanyi na kyakukola'},
                      {'end': 147.73784,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'caller',
                       'start': 145.51034,
                       'text': 'atutte eddaala eddene okunkubira leero'},
                      {'end': 154.13347,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 149.64472,
                       'text': 'osobola okujja ebutabika enkya okwongera '
                               'okufuna obuyambi obusingako'},
                      {'end': 156.58034,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 155.36534,
                       'text': 'ndowooza asobola'},
                      {'end': 159.04409,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'agent',
                       'start': 157.00222,
                       'text': 'kino tujja kukiyitamu ffembemeriyam'},
                      {'end': 161.22097,
                       'language': 'lug',
                       'speaker': 'SPEAKER_00',
                       'speaker_role_id': 'caller',
                       'start': 159.76972,
                       'text': 'weebale nnyo tania'},
                      {'end': 163.61722,
                       'language': 'lug',
                       'speaker': 'SPEAKER_01',
                       'speaker_role_id': 'caller',
                       'start': 161.38972,
                       'text': 'kale akawungeezi akalungi'}]}

res = requests.post("http://100.104.98.125:8555/predict_symptoms", json=payload)
print(json.dumps(res.json(), indent=2))
