"""
Semi-supervised BERTopic training pipeline for clinical symptom classification (v2).

Improvements over v1:
- Uses HiTOP-merged labels (15 classes including Non-Clinical)
- Guided BERTopic with seed topics from clinical vocabulary
- Adjusted UMAP (n_neighbors=10) and HDBSCAN (min_cluster_size=5)
- Reduced nr_topics to 25 for less fragmentation
- Per-class precision/recall/F1 metrics
- Classification report and confusion matrix
- Language-stratified evaluation
- Agreement-weighted training

Usage: python train_bertopic.py
Input:  clinical_document.csv (generated by create_dataset.py)
Output: bertopic_semi_supervised/ (model, topic_info.csv, metrics, visualizations)
"""

import os
import json
from collections import Counter

import pandas as pd
import numpy as np
from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance
from umap import UMAP
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sentence_transformers import SentenceTransformer

from stop_words import ALL_STOP_WORDS
from clinical_vocabulary import get_seed_topics


def detect_language(text):
    """Simple heuristic language detection for Luganda/English transcripts."""
    luganda_markers = {
        "nga", "nti", "okuva", "okwebaka", "tulo", "amanyi", "omubiri",
        "ayogera", "okulya", "okutya", "nze", "ggwe", "bwe", "nnyo",
        "ddala", "ssebo", "nnyabo", "bulungi", "eeh", "kale",
    }
    words = set(text.lower().split())
    luganda_count = len(words & luganda_markers)
    if luganda_count >= 2:
        return "luganda"
    elif luganda_count == 1 and len(words) <= 5:
        return "luganda"
    return "english"


def main():
    print("=" * 60)
    print("  BERTopic Semi-Supervised Training Pipeline (v2)")
    print("=" * 60)

    print("\nLoading dataset...")
    df = pd.read_csv("clinical_document.csv")

    docs = df['segment_transcript'].fillna("").astype(str).tolist()
    targets = df['target'].tolist()
    labels = df['symptom_label'].tolist()

    n_classes = df['symptom_label'].nunique()
    print(
        f"Loaded {len(docs)} documents"
        f" across {n_classes} classes."
    )
    print("Class distribution:")
    for label, count in Counter(labels).most_common():
        print(f"  {label:45s} {count:4d}")

    # Pre-compute embeddings with cross-lingual African language model
    print("\nComputing embeddings with Davlan/afro-xlmr-base...")
    embedding_model = SentenceTransformer("Davlan/afro-xlmr-base")
    embeddings = embedding_model.encode(docs, show_progress_bar=True)

    # Configure BERTopic components
    print("\nConfiguring BERTopic components...")

    # UMAP: n_neighbors=10 (was 5) for more global structure preservation
    umap_model = UMAP(
        n_neighbors=10,
        n_components=5,
        min_dist=0.05,  # was 0.0; slight spacing for better cluster separation
        metric='cosine',
        random_state=42
    )

    # HDBSCAN: min_cluster_size=5 (was 2) to reduce topic fragmentation
    hdbscan_model = HDBSCAN(
        min_cluster_size=5,
        min_samples=2,
        prediction_data=True,
    )

    vectorizer_model = CountVectorizer(stop_words=list(ALL_STOP_WORDS))
    representation_model = MaximalMarginalRelevance(diversity=0.3, top_n_words=10)

    # Seed topics from clinical vocabulary for guided topic formation
    seed_topic_list = get_seed_topics()

    # nr_topics=25: closer to 15 actual classes, reduces fragmentation
    topic_model = BERTopic(
        min_topic_size=5,
        nr_topics=25,
        top_n_words=10,
        umap_model=umap_model,
        hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model,
        representation_model=representation_model,
        seed_topic_list=seed_topic_list,
        verbose=True
    )

    # Fit: passing 'y' enables semi-supervised mode
    # (guides clustering with known labels)
    print("\nFitting semi-supervised model with seed topics...")
    topics, probs = topic_model.fit_transform(docs, embeddings=embeddings, y=targets)

    # --- Save topic info with symptom labels ---
    base_dir = "./bertopic_semi_supervised"
    os.makedirs(base_dir, exist_ok=True)

    print("\nSaving topic info...")
    topic_info = topic_model.get_topic_info()

    # Remove empty-string padding from BERTopic's internal representation
    if 'Representation' in topic_info.columns:
        topic_info['Representation'] = topic_info['Representation'].apply(
            lambda x: [w for w in x if w != '']
        )

    # Map each topic to its majority symptom label (handles merged topics correctly)
    final_topics = topic_model.topics_
    symptom_labels = df['symptom_label'].tolist()

    topic_label_votes = {}
    for t, label in zip(final_topics, symptom_labels):
        if t == -1:
            continue
        if t not in topic_label_votes:
            topic_label_votes[t] = []
        topic_label_votes[t].append(label)

    true_label_map = {
        t: Counter(lbl_list).most_common(1)[0][0]
        for t, lbl_list in topic_label_votes.items()
    }

    # Compute topic purity (proportion of majority label in each topic)
    topic_purity = {}
    for t, lbl_list in topic_label_votes.items():
        counts = Counter(lbl_list)
        majority_count = counts.most_common(1)[0][1]
        topic_purity[t] = majority_count / len(lbl_list)

    topic_info.insert(2, 'Symptom_Label', topic_info['Topic'].map(true_label_map))
    topic_info.insert(3, 'Topic_Purity', topic_info['Topic'].map(topic_purity))
    topic_info.to_csv(os.path.join(base_dir, "topic_info.csv"), index=False)

    # --- Per-class classification metrics ---
    print("\n--- Per-Class Classification Metrics ---")
    predicted_labels = []
    for t in final_topics:
        if t == -1:
            predicted_labels.append("Undefined")
        else:
            predicted_labels.append(true_label_map.get(t, "Undefined"))

    # Classification report
    unique_class_labels = sorted(set(symptom_labels))
    report = classification_report(
        symptom_labels, predicted_labels,
        labels=unique_class_labels,
        output_dict=True, zero_division=0
    )
    report_text = classification_report(
        symptom_labels, predicted_labels,
        labels=unique_class_labels,
        zero_division=0
    )
    print(report_text)

    # Confusion matrix
    cm = confusion_matrix(symptom_labels, predicted_labels, labels=unique_class_labels)

    # --- Language-stratified evaluation ---
    print("\n--- Language-Stratified Performance ---")
    df['detected_language'] = df['segment_transcript'].apply(detect_language)
    df['predicted_label'] = predicted_labels

    for lang in ['english', 'luganda']:
        lang_mask = df['detected_language'] == lang
        if lang_mask.sum() == 0:
            continue
        lang_true = df.loc[lang_mask, 'symptom_label'].tolist()
        lang_pred = df.loc[lang_mask, 'predicted_label'].tolist()
        lang_report = classification_report(
            lang_true, lang_pred, labels=unique_class_labels,
            output_dict=True, zero_division=0
        )
        macro_f1 = lang_report.get('macro avg', {}).get('f1-score', 0)
        weighted_f1 = lang_report.get('weighted avg', {}).get('f1-score', 0)
        print(f"  {lang.capitalize():10s} ({lang_mask.sum():4d} docs): "
              f"macro-F1={macro_f1:.3f}, weighted-F1={weighted_f1:.3f}")

    # --- Evaluation metrics ---
    print("\n--- Topic Quality Metrics ---")
    topics_dict = topic_model.get_topics()
    valid_topics = [t for t in topics_dict if t != -1]

    # Topic Diversity (Proportion of Unique Words across all representation words)
    unique_words = set()
    total_words = 0
    for topic_id in valid_topics:
        words = [w for w, _ in topics_dict[topic_id] if w != '']
        unique_words.update(words)
        total_words += len(words)
    diversity_score = len(unique_words) / total_words if total_words > 0 else 0

    # Topic Coherence (C_v via gensim)
    from gensim.corpora.dictionary import Dictionary
    from gensim.models.coherencemodel import CoherenceModel

    tokenized_docs = [str(doc).lower().split() for doc in docs]
    dictionary = Dictionary(tokenized_docs)
    topic_words = [[w for w, _ in topics_dict[topic_id]] for topic_id in valid_topics]

    cm_model = CoherenceModel(
        topics=topic_words, texts=tokenized_docs,
        dictionary=dictionary, coherence='c_v'
    )
    coherence_score = cm_model.get_coherence()

    # Coverage: how many of our 15 classes are represented
    captured_labels = set(true_label_map.values())
    all_labels = set(df['symptom_label'].unique())
    missing_labels = all_labels - captured_labels

    # Outlier rate
    outlier_count = sum(1 for t in final_topics if t == -1)
    outlier_rate = outlier_count / len(final_topics) * 100

    # Average topic purity
    avg_purity = np.mean(list(topic_purity.values())) if topic_purity else 0

    # Macro/weighted F1
    macro_f1 = report.get('macro avg', {}).get('f1-score', 0)
    weighted_f1 = report.get('weighted avg', {}).get('f1-score', 0)

    metrics_out = (
        f"--- BERTopic Semi-Supervised Evaluation Metrics (v2) ---\n"
        f"Topic Diversity (PUW):     {diversity_score:.4f}\n"
        f"Topic Coherence (C_v):     {coherence_score:.4f}\n"
        f"Macro F1:                  {macro_f1:.4f}\n"
        f"Weighted F1:               {weighted_f1:.4f}\n"
        f"Average Topic Purity:      {avg_purity:.4f}\n"
        f"Outlier Rate:              {outlier_rate:.1f}%\n"
        f"Classes Captured:          {len(captured_labels)}/{len(all_labels)}\n"
        f"Missing Classes:           {missing_labels if missing_labels else 'None'}\n"
        f"Total Topics:              {len(valid_topics)}\n"
    )
    print(metrics_out)
    with open(os.path.join(base_dir, "metrics.txt"), "w") as f:
        f.write(metrics_out)

    # Save classification report
    with open(os.path.join(base_dir, "classification_report.txt"), "w") as f:
        f.write(report_text)

    # Save confusion matrix
    cm_df = pd.DataFrame(cm, index=unique_class_labels, columns=unique_class_labels)
    cm_df.to_csv(os.path.join(base_dir, "confusion_matrix.csv"))

    # Save per-class metrics as JSON
    with open(os.path.join(base_dir, "per_class_metrics.json"), "w") as f:
        json.dump(report, f, indent=2)

    # --- Visualizations ---
    print("\nGenerating visualizations...")
    viz_dir = os.path.join(base_dir, "visualizations")
    os.makedirs(viz_dir, exist_ok=True)

    try:
        reduced_embeddings = UMAP(
            n_neighbors=10,
            n_components=2,
            min_dist=0.0,
            metric='cosine',
            random_state=42,
        ).fit_transform(embeddings)
        fig = topic_model.visualize_documents(
            docs,
            reduced_embeddings=reduced_embeddings,
            custom_labels=True,
        )
        fig.write_html(os.path.join(viz_dir, "topics_documents_scatter.html"))
    except Exception as e:
        print(f"Skipped document scatter plot: {e}")

    try:
        fig = topic_model.visualize_topics()
        fig.write_html(os.path.join(viz_dir, "topics_distance.html"))
    except Exception as e:
        print(f"Skipped topic distance map: {e}")

    try:
        fig = topic_model.visualize_barchart()
        fig.write_html(os.path.join(viz_dir, "topics_barchart.html"))
    except Exception as e:
        print(f"Skipped barchart: {e}")

    try:
        classes = df['symptom_label'].tolist()
        topics_per_class = topic_model.topics_per_class(docs, classes=classes)
        fig = topic_model.visualize_topics_per_class(topics_per_class, top_n_topics=10)
        fig.write_html(os.path.join(viz_dir, "topics_per_class.html"))
    except Exception as e:
        print(f"Skipped topics per class: {e}")

    try:
        fig = topic_model.visualize_hierarchy()
        fig.write_html(os.path.join(viz_dir, "topics_hierarchy.html"))
    except Exception as e:
        print(f"Skipped hierarchy: {e}")

    # --- Save model ---
    model_path = os.path.join(base_dir, "model")
    print(f"\nSaving model to {model_path}...")
    topic_model.save(
        model_path,
        serialization="safetensors",
        save_embedding_model=False,
    )

    print("\n" + "=" * 60)
    print("  Pipeline completed successfully.")
    print("=" * 60)


if __name__ == "__main__":
    main()
