"""
Ordinal Likelihood Affect Risk Model (MODEL-3).

Predicts the likelihood (1=unlikely, 2=possible, 3=likely) that a caller
exhibits psychosis, depression, or anxiety risk, based on transcript
embeddings from Davlan/afro-xlmr-base.

Architecture:
  - Three independent ordinal classifiers (one per risk category)
  - OrdinalClassifier wraps LogisticRegression with ordinal thresholding
  - Multi-label: a single transcript can score on all three categories
  - Clinician-confirmed labels used for confidence weighting

Data: affect_risk_dataset.csv (190 files, generated by create_dataset.py)
  - Psychosis scored: 138 files (1: 66, 2: 42, 3: 30)
  - Depression scored: 88 files (1: 43, 2: 29, 3: 16)
  - Anxiety scored: 42 files (1: 31, 2: 5, 3: 6)

Usage: python train_affect_risk.py
Output: affect_risk_model/ (models, metrics, evaluation)
"""

import os
import json
import warnings
from collections import Counter

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, LeaveOneOut
from sklearn.metrics import (
    classification_report, confusion_matrix,
    mean_absolute_error, cohen_kappa_score
)
from sentence_transformers import SentenceTransformer
import joblib

warnings.filterwarnings("ignore", category=FutureWarning)


class OrdinalClassifier:
    """
    Ordinal regression via cumulative threshold approach.

    Instead of treating ordinal labels as unrelated categories,
    this fits K-1 binary classifiers for P(Y > k) and combines
    them to produce ordinal predictions.

    For 3 ordinal levels (1, 2, 3):
      - clf_1: P(Y > 1) — separates level 1 from {2, 3}
      - clf_2: P(Y > 2) — separates {1, 2} from level 3

    Final prediction uses cumulative probabilities:
      P(Y = 1) = 1 - P(Y > 1)
      P(Y = 2) = P(Y > 1) - P(Y > 2)
      P(Y = 3) = P(Y > 2)
    """

    def __init__(self, base_clf=None):
        self.base_clf = base_clf or LogisticRegression(
            max_iter=1000, solver='lbfgs', C=1.0, random_state=42
        )
        self.clfs = {}
        self.classes_ = None

    def fit(self, X, y, sample_weight=None):
        self.classes_ = np.sort(np.unique(y))
        # Fit K-1 binary classifiers
        for k in self.classes_[:-1]:
            binary_y = (y > k).astype(int)
            clf = LogisticRegression(
                max_iter=1000, solver='lbfgs', C=1.0, random_state=42
            )
            # Only fit if both classes exist
            if len(np.unique(binary_y)) > 1:
                clf.fit(X, binary_y, sample_weight=sample_weight)
            else:
                # Degenerate case — always predict the single class
                clf = None
            self.clfs[k] = clf
        return self

    def predict_proba(self, X):
        """Return probability for each ordinal level."""
        n = X.shape[0]
        n_classes = len(self.classes_)
        proba = np.zeros((n, n_classes))

        # Get cumulative probabilities P(Y > k)
        cum_probs = {}
        for k in self.classes_[:-1]:
            clf = self.clfs[k]
            if clf is not None:
                cum_probs[k] = clf.predict_proba(X)[:, 1]
            else:
                cum_probs[k] = np.zeros(n)

        # Convert cumulative to category probabilities
        # P(Y = first_class) = 1 - P(Y > first_class)
        proba[:, 0] = 1 - cum_probs[self.classes_[0]]
        # P(Y = last_class) = P(Y > second_to_last)
        proba[:, -1] = cum_probs[self.classes_[-2]]
        # P(Y = middle_k) = P(Y > k-1) - P(Y > k)
        for i in range(1, n_classes - 1):
            proba[:, i] = cum_probs[self.classes_[i-1]] - cum_probs[self.classes_[i]]

        # Clip and normalize (numerical stability)
        proba = np.clip(proba, 0, 1)
        row_sums = proba.sum(axis=1, keepdims=True)
        row_sums[row_sums == 0] = 1
        proba = proba / row_sums

        return proba

    def predict(self, X):
        proba = self.predict_proba(X)
        return self.classes_[np.argmax(proba, axis=1)]


def evaluate_ordinal_model(y_true, y_pred, category_name, class_labels):
    """Compute ordinal-appropriate metrics."""
    metrics = {}

    # Mean Absolute Error (ordinal distance)
    metrics['mae'] = mean_absolute_error(y_true, y_pred)

    # Quadratic Weighted Kappa (ordinal agreement)
    metrics['qwk'] = cohen_kappa_score(y_true, y_pred, weights='quadratic')

    # Standard classification metrics
    report = classification_report(
        y_true, y_pred,
        labels=class_labels,
        target_names=[f"L{lv}" for lv in class_labels],
        output_dict=True,
        zero_division=0
    )
    metrics['macro_f1'] = report['macro avg']['f1-score']
    metrics['weighted_f1'] = report['weighted avg']['f1-score']

    # Adjacency accuracy (within 1 level)
    metrics['adj_accuracy'] = np.mean(np.abs(y_true - y_pred) <= 1)

    # Exact accuracy
    metrics['exact_accuracy'] = np.mean(y_true == y_pred)

    return metrics, report


def train_category_model(X_all, y_all, weights, category_name, out_dir):
    """Train and evaluate ordinal model for a single risk category."""
    print(f"\n{'='*50}")
    print(f"  {category_name} Risk Model")
    print(f"{'='*50}")

    # Filter to non-NaN entries
    mask = ~np.isnan(y_all)
    X = X_all[mask]
    y = y_all[mask].astype(int)
    w = weights[mask] if weights is not None else None

    n_samples = len(y)
    class_labels = np.array([1, 2, 3])
    print(f"  Samples: {n_samples}")
    print(f"  Distribution: {dict(Counter(y))}")

    if n_samples < 10:
        print(f"  ⚠ Too few samples for {category_name}. Skipping CV.")
        # Train on all data anyway
        model = OrdinalClassifier()
        model.fit(X, y, sample_weight=w)
        joblib.dump(
            model,
            os.path.join(
                out_dir,
                f"{category_name.lower()}_model.joblib",
            ),
        )
        return None

    # Choose CV strategy based on sample size
    min_class_count = min(Counter(y).values())
    if min_class_count < 5:
        # Use Leave-One-Out for very small classes
        print(f"  CV strategy: Leave-One-Out (min class count = {min_class_count})")
        cv = LeaveOneOut()
        all_true = []
        all_pred = []
        all_proba = []

        for train_idx, val_idx in cv.split(X, y):
            X_train, X_val = X[train_idx], X[val_idx]
            y_train, y_val = y[train_idx], y[val_idx]
            w_train = w[train_idx] if w is not None else None

            model = OrdinalClassifier()
            model.fit(X_train, y_train, sample_weight=w_train)

            pred = model.predict(X_val)
            proba = model.predict_proba(X_val)

            all_true.extend(y_val.tolist())
            all_pred.extend(pred.tolist())
            all_proba.extend(proba.tolist())

        all_true = np.array(all_true)
        all_pred = np.array(all_pred)
    else:
        # Stratified K-Fold
        n_splits = min(5, min_class_count)
        print(f"  CV strategy: {n_splits}-fold stratified")
        skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

        all_true = []
        all_pred = []
        all_proba = []


        for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):
            X_train, X_val = X[train_idx], X[val_idx]
            y_train, y_val = y[train_idx], y[val_idx]
            w_train = w[train_idx] if w is not None else None

            model = OrdinalClassifier()
            model.fit(X_train, y_train, sample_weight=w_train)

            pred = model.predict(X_val)
            proba = model.predict_proba(X_val)

            mae = mean_absolute_error(y_val, pred)
            adj_acc = np.mean(np.abs(y_val - pred) <= 1)
            print(f"    Fold {fold+1}: MAE={mae:.3f}, Adj.Accuracy={adj_acc:.3f}")

            all_true.extend(y_val.tolist())
            all_pred.extend(pred.tolist())
            all_proba.extend(proba.tolist())

        all_true = np.array(all_true)
        all_pred = np.array(all_pred)

    # Aggregate metrics
    metrics, report = evaluate_ordinal_model(
        all_true, all_pred, category_name, class_labels
    )

    print(f"\n  --- {category_name} Results ---")
    print(f"  MAE:                {metrics['mae']:.4f}")
    print(f"  Quadratic W. Kappa: {metrics['qwk']:.4f}")
    print(f"  Macro F1:           {metrics['macro_f1']:.4f}")
    print(f"  Weighted F1:        {metrics['weighted_f1']:.4f}")
    print(f"  Exact Accuracy:     {metrics['exact_accuracy']:.4f}")
    print(f"  Adjacent Accuracy:  {metrics['adj_accuracy']:.4f}")

    # Classification report
    report_text = classification_report(
        all_true, all_pred,
        labels=class_labels,
        target_names=["Unlikely (1)", "Possible (2)", "Likely (3)"],
        zero_division=0
    )
    print(f"\n{report_text}")

    # Confusion matrix
    cm = confusion_matrix(all_true, all_pred, labels=class_labels)
    print("  Confusion Matrix:")
    print(f"  {'':15s} Pred 1  Pred 2  Pred 3")
    for i, label in enumerate(class_labels):
        print(f"  True {label}:       {cm[i][0]:5d}   {cm[i][1]:5d}   {cm[i][2]:5d}")

    # Train final model on all data
    final_model = OrdinalClassifier()
    final_model.fit(X, y, sample_weight=w)

    # Save artifacts
    cat_dir = os.path.join(out_dir, category_name.lower())
    os.makedirs(cat_dir, exist_ok=True)

    joblib.dump(final_model, os.path.join(cat_dir, "model.joblib"))

    with open(os.path.join(cat_dir, "metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    with open(os.path.join(cat_dir, "classification_report.txt"), "w") as f:
        f.write(report_text)

    cm_df = pd.DataFrame(
        cm,
        index=["True_1", "True_2", "True_3"],
        columns=["Pred_1", "Pred_2", "Pred_3"]
    )
    cm_df.to_csv(os.path.join(cat_dir, "confusion_matrix.csv"))

    return metrics


def main():
    print("=" * 60)
    print("  Affect Risk Ordinal Likelihood Model (MODEL-3)")
    print("=" * 60)

    # --- Load data ---
    print("\nLoading affect risk dataset...")
    df = pd.read_csv("affect_risk_dataset.csv")
    print(f"Loaded {len(df)} files.")

    # Use full_transcript for embedding (clinical transcripts)
    # Fall back to empty string for files without transcripts
    transcripts = df['full_transcript'].fillna("").astype(str).tolist()

    # Confirmed flags as confidence weights
    # Confirmed = 1.0, Not confirmed = 0.7 (still informative)
    psychosis_weights = np.where(df['psychosis_confirmed'].fillna(False), 1.0, 0.7)
    depression_weights = np.where(df['depression_confirmed'].fillna(False), 1.0, 0.7)
    anxiety_weights = np.where(df['anxiety_confirmed'].fillna(False), 1.0, 0.7)

    # --- Compute embeddings ---
    print("\nComputing embeddings with Davlan/afro-xlmr-base...")
    embedding_model = SentenceTransformer("Davlan/afro-xlmr-base")
    X = embedding_model.encode(transcripts, show_progress_bar=True)

    # --- Train per-category models ---
    out_dir = "./affect_risk_model"
    os.makedirs(out_dir, exist_ok=True)

    results = {}

    # Psychosis (138 scored)
    results['psychosis'] = train_category_model(
        X, df['psychosis_score'].values, psychosis_weights,
        "Psychosis", out_dir
    )

    # Depression (88 scored)
    results['depression'] = train_category_model(
        X, df['depression_score'].values, depression_weights,
        "Depression", out_dir
    )

    # Anxiety (42 scored)
    results['anxiety'] = train_category_model(
        X, df['anxiety_score'].values, anxiety_weights,
        "Anxiety", out_dir
    )

    # --- Save summary ---
    print("\n" + "=" * 60)
    print("  Summary")
    print("=" * 60)

    summary = "--- Affect Risk Model Summary ---\n\n"
    summary += (
        f"{'Category':15s} {'MAE':>8s} {'QWK':>8s}"
        f" {'Macro-F1':>10s} {'Adj.Acc':>10s}"
        f" {'Samples':>8s}\n"
    )
    summary += "-" * 65 + "\n"

    for cat_name in ['psychosis', 'depression', 'anxiety']:
        m = results[cat_name]
        if m is None:
            summary += (
                f"{cat_name:15s}"
                f" {'N/A':>8s} {'N/A':>8s}"
                f" {'N/A':>10s} {'N/A':>10s}"
                f" {'<10':>8s}\n"
            )
        else:
            n_samples = int(df[f'{cat_name}_score'].notna().sum())
            summary += (
                f"{cat_name:15s} {m['mae']:8.4f} {m['qwk']:8.4f} "
                f"{m['macro_f1']:10.4f} {m['adj_accuracy']:10.4f} {n_samples:8d}\n"
            )

    print(summary)

    with open(os.path.join(out_dir, "summary.txt"), "w") as f:
        f.write(summary)

    with open(os.path.join(out_dir, "all_metrics.json"), "w") as f:
        json.dump({k: v for k, v in results.items() if v is not None}, f, indent=2)

    # Save embedding model name for inference
    with open(os.path.join(out_dir, "config.json"), "w") as f:
        json.dump({
            "embedding_model": "Davlan/afro-xlmr-base",
            "categories": ["psychosis", "depression", "anxiety"],
            "ordinal_levels": [1, 2, 3],
            "level_labels": {
                "1": "Unlikely",
                "2": "Possible",
                "3": "Likely"
            }
        }, f, indent=2)

    print(f"\nSaved to {out_dir}/")
    print("=" * 60)


if __name__ == "__main__":
    main()
