"""
Supervised BERTopic training pipeline for clinical symptom classification.

Uses pre-defined symptom labels as explicit cluster assignments (bypassing
UMAP and HDBSCAN). Produces a 1:1 mapping between topics and symptom classes.

This pipeline is retained for comparison and evaluation purposes.
The semi-supervised pipeline (train_bertopic.py) is used in production.

Usage: python train_supervised_bertopic.py
Input:  clinical_document.csv (generated by create_dataset.py)
Output: bertopic_supervised/ (model, topic_info.csv, metrics, visualizations)
"""

import os

import pandas as pd
from bertopic import BERTopic
from bertopic.representation import MaximalMarginalRelevance
from bertopic.backend import BaseEmbedder
from bertopic.cluster import BaseCluster
from bertopic.dimensionality import BaseDimensionalityReduction
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
from umap import UMAP

from stop_words import ALL_STOP_WORDS


def main():
    print("Loading dataset...")
    df = pd.read_csv("clinical_document.csv")

    docs = df['segment_transcript'].fillna("").astype(str).tolist()
    targets = df['target'].tolist()

    print(f"Loaded {len(docs)} documents.")

    # Pre-compute embeddings with cross-lingual African language model
    print("\nComputing embeddings with Davlan/afro-xlmr-base...")
    embedding_model = SentenceTransformer("Davlan/afro-xlmr-base")
    embeddings = embedding_model.encode(docs, show_progress_bar=True)

    # Supervised mode: bypass dimensionality reduction and clustering
    # BERTopic uses the provided labels directly as cluster assignments
    print("\nConfiguring supervised BERTopic...")
    empty_dimensionality_model = BaseDimensionalityReduction()
    empty_cluster_model = BaseCluster()

    vectorizer_model = CountVectorizer(stop_words=list(ALL_STOP_WORDS))
    representation_model = MaximalMarginalRelevance(diversity=0.3, top_n_words=3)

    topic_model = BERTopic(
        top_n_words=3,
        umap_model=empty_dimensionality_model,
        hdbscan_model=empty_cluster_model,
        vectorizer_model=vectorizer_model,
        representation_model=representation_model,
        verbose=True
    )

    print("Fitting supervised model...")
    topics, probs = topic_model.fit_transform(docs, embeddings=embeddings, y=targets)

    # --- Save topic info with symptom labels ---
    base_dir = "./bertopic_supervised"
    os.makedirs(base_dir, exist_ok=True)

    print("\nSaving topic info...")
    topic_info = topic_model.get_topic_info()

    # Prune empty-string padding from BERTopic's internal representation
    if 'Representation' in topic_info.columns:
        topic_info['Representation'] = topic_info['Representation'].apply(
            lambda x: [w for w in x if w != ''][:3]
        )

    # Map topics to symptom labels (exclude outlier topic -1)
    true_label_map = {t: l for t, l in zip(topics, df['symptom_label'].tolist()) if t != -1}
    topic_info.insert(2, 'Symptom_Label', topic_info['Topic'].map(true_label_map))

    topic_info.to_csv(os.path.join(base_dir, "topic_info.csv"), index=False)

    # --- Evaluation metrics ---
    print("\nComputing evaluation metrics...")
    topics_dict = topic_model.get_topics()
    valid_topics = [t for t in topics_dict if t != -1]

    # Topic Diversity (Proportion of Unique Words)
    top_n = 3
    unique_words = set()
    total_words = 0
    for topic_id in valid_topics:
        words = [w for w, _ in topics_dict[topic_id][:top_n]]
        unique_words.update(words)
        total_words += len(words)
    diversity_score = len(unique_words) / total_words if total_words > 0 else 0

    # Topic Coherence (C_v via gensim)
    from gensim.corpora.dictionary import Dictionary
    from gensim.models.coherencemodel import CoherenceModel

    tokenized_docs = [str(doc).lower().split() for doc in docs]
    dictionary = Dictionary(tokenized_docs)
    topic_words = [[w for w, _ in topics_dict[topic_id]] for topic_id in valid_topics]

    cm = CoherenceModel(topics=topic_words, texts=tokenized_docs, dictionary=dictionary, coherence='c_v')
    coherence_score = cm.get_coherence()

    metrics_out = (
        f"--- BERTopic Supervised Evaluation Metrics ---\n"
        f"Topic Diversity (PUW): {diversity_score:.4f}\n"
        f"Topic Coherence (C_v): {coherence_score:.4f}\n"
    )
    print(metrics_out)
    with open(os.path.join(base_dir, "metrics.txt"), "w") as f:
        f.write(metrics_out)

    # --- Visualizations ---
    print("\nGenerating visualizations...")
    viz_dir = os.path.join(base_dir, "visualizations")
    os.makedirs(viz_dir, exist_ok=True)

    try:
        reduced_embeddings = UMAP(
            n_neighbors=10, n_components=2, min_dist=0.0, metric='cosine', random_state=42
        ).fit_transform(embeddings)
        fig = topic_model.visualize_documents(docs, reduced_embeddings=reduced_embeddings, custom_labels=True)
        fig.write_html(os.path.join(viz_dir, "topics_documents_scatter.html"))
    except Exception as e:
        print(f"Skipped document scatter plot: {e}")

    try:
        fig = topic_model.visualize_topics()
        fig.write_html(os.path.join(viz_dir, "topics_distance.html"))
    except Exception as e:
        print(f"Skipped topic distance map: {e}")

    try:
        fig = topic_model.visualize_barchart()
        fig.write_html(os.path.join(viz_dir, "topics_barchart.html"))
    except Exception as e:
        print(f"Skipped barchart: {e}")

    try:
        classes = df['symptom_label'].tolist()
        topics_per_class = topic_model.topics_per_class(docs, classes=classes)
        fig = topic_model.visualize_topics_per_class(topics_per_class, top_n_topics=10)
        fig.write_html(os.path.join(viz_dir, "topics_per_class.html"))
    except Exception as e:
        print(f"Skipped topics per class: {e}")

    try:
        fig = topic_model.visualize_hierarchy()
        fig.write_html(os.path.join(viz_dir, "topics_hierarchy.html"))
    except Exception as e:
        print(f"Skipped hierarchy: {e}")

    # --- Save model ---
    model_path = os.path.join(base_dir, "model")
    print(f"\nSaving model to {model_path}...")
    topic_model.save(model_path, serialization="safetensors", save_embedding_model=False)

    print("Pipeline completed successfully.")


if __name__ == "__main__":
    main()
